### ISSUE TITLE
IdP sends successful LogoutResponse from AuthnRequest?

### ISSUE THREAD

**Issue by richardrowe** [onelogin/php-saml#329]
I am using the `onelogin/php-saml` library to allow a Service Provider (SP) to initiate auth requests to an IdP (OneLogin) with SP, IdP, organisation and security settings that roughly described below:

```
 idp:
      entityId: "https://app.onelogin.com/saml/metadata/<metadataID>"
      singleLogoutService:
        binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        url: "https://<subdomain>.onelogin.com/client/apps"
      singleSignOnService:
        binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        url: "<http-redirect-slo-url>"
      # public key for x509 cert in OneLogin
      certFingerprint: "<pubkey>"
      certFingerprintAlgorithm: "sha256"
sp:
      assertionConsumerService:
        binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Post"
        url: "<SPACSEndpoint>"
      entityId: "<SPMetadataEndpoint>"
      singleLogoutService:
        binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        url: "<SPLogoutEndpoint>"
      NameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"

security:
      authnRequestsSigned: false
      logoutRequestSigned: false
      logoutResponseSigned: false
      nameIdEncrypted: false
      requestedAuthnContext: true
      signMetadata: false
      signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
      wantAssertionsSigned: false
      wantMessagesSigned: false
      wantNameIdEncrypted: false
      wantXMLValidation: true
```

I make a GET request on the Service Provider to `saml/login` that checks if the user is already authenticated on the SP, and if not, to call `php-saml`'s `->login()` method which sends a GET SAMLRequest to the IdP using the `http-redirect/slo` endpoint.  It looks something like this:
 
```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID=""
                    Version="2.0"
                    ProviderName="<placeholder>"
                    IsPassive="true"
                    IssueInstant="2018-07-11T23:13:29Z"
                    Destination="https://<domain>.onelogin.com/trust/saml2/http-redirect/slo/<id>"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Post"
                    AssertionConsumerServiceURL="<SPACSEndpoint>"
                    >
    <saml:Issuer><SPMetadataEndpoint></saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
                        AllowCreate="true"
                        />
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

the IdP then comes back with a `LogoutResponse` (even though the *user is already authenticated at the IdP*).

```
<samlp:LogoutResponse IssueInstant="2018-07-11T23:13:27Z"
                      Version="2.0"
                      ID=""
                      xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                      > <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://app.onelogin.com/saml/metadata/<metadataId></saml:Issuer> <samlp:Status> <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /> <samlp:StatusMessage>Successfully logged out from service </samlp:StatusMessage> </samlp:Status> </samlp:LogoutResponse>
```

which ultimately redirects the user to the IdP's login page.

I was expecting the IdP to call the ACS endpoint on the SP to tell the SP the user is already authenticated on the IdP, for the SP to authenticate the user.

I suspect this is caused by a mis-configuration.  I don't have visibility into what the IdP is doing to determine sending back a LogoutResponse instead of calling our ACS endpoint.

The ultimate problem I'm trying to solve here is for OneLogin to not prompt for MFA when being accessed from the IdP side if the SP/IdP is already authenticated.

Any help/guidance would be appreciated.
